### ISSUE TITLE
Jump to schema.rb for models

### ISSUE THREAD

**Issue by swe9** [gurgeous/bust-a-gem#2]
In a model file, highlight the class name and invoke go-to-definition.  You land right where you started :-)  

It would be very helpful if that command would take you to the schema.rb section showing the table structure for the model.  The other approach looks like https://github.com/ctran/annotate_models, but it's static and a bit messy compared to just jumping to the relevant information.  The rails console can give similar info with Model.column_names, but then you have to be in the rails console...

**Comment by gurgeous** [comment]
Neat idea. Happy to consider a PR if you have an easy way to implement... I love the `annotate` gem and I use it in all my projects. I'll reopen if you come up with a PR. Thanks!
