### ISSUE TITLE
Use tags to populate workspace symbols

### ISSUE THREAD

**Issue by matteeyah** [gurgeous/bust-a-gem#6]
The extension should be able to use the tags file for populating symbols. This way, it should enable both navigating to workspace and in-file symbols easily.

**Comment by gurgeous** [comment]
I actually did that on purpose since I prefer it that way :) But a few people want it to work the other way and that would be fine with me too. There's currently an open PR that switches the behavior #5, so closing this. Thanks for the feedback!

**Comment by gurgeous** [comment]
Oops, meant this comment for the other issue. Hang on...

**Comment by gurgeous** [comment]
If I remember correctly, I tried that in the beginning and found it unsatisfying for some reason. I also don't use that feature (Go To Symbol In Workspace) very often. Feel free to submit a PR if you want it, though. Thanks for the feedback!
