### ISSUE TITLE
Symbols include preceding keyword

### ISSUE THREAD

**Issue by matteeyah** [gurgeous/bust-a-gem#7]
When navigating to symbols inside a file, they include the preceding definition keyword.

e.g. when I want to navigate to a method called `foobar` the jump to symbol dropdown lists it as `def foobar`. 

This can likely be fixed by narrowing the symbol regex capture group to not include the keyword itself.

**Comment by gurgeous** [comment]
I actually did that on purpose since I prefer it that way :) But a few people want it to work the other way and that would be fine with me too. There's currently an open PR that switches the behavior #5, so closing this. Thanks for the feedback!
