### ISSUE TITLE
 Load Several tags Files

### ISSUE THREAD

**Issue by feber** [gurgeous/bust-a-gem#9]
Hello,
Is it possible to load several tags file like what we have in Vim?
For exampe we have a TAGS contains our code (e.g. `lib/`) and GEMTAGS for libraries (e.g. `vendor/`).

How may I help?
Thanks!

**Comment by gurgeous** [comment]
Glad you like it! I don't really have a plan for loading multiple TAGS files. I recognize that this is sorta lame. In the meantime, you can build/cat the TAGS files together manually.

Feel free to dig in with a PR, though I suspect it will be somewhat complicated.
